version: '2'
services:
  master:
    build: .
    image: aprenderdevops/jenkins:latest
    restart: unless-stopped
    hostname: jenkins
    ports:
      - "9080:9080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: